### PR TITLE
Add UI for Cart Page

### PR DESCRIPTION
**Pull request by DanCat6300**
**Description:** 

- Add UI for user's cart 
- Cart shows a list of added movies and can scroll if overflow 
- Display movie thumbnail, name, duration, publish year and price
- The total price is displayed below the list
- Checkout and Remove button is not functional yet

Capture

### CODE REVIEW

**Review by hongnguyen0112 — APPROVED** [review]

**Comment by hongnguyen0112** [comment]
**Description**

- Remove button is functional
- Fix bug in cart when logged out 
- Checkout button remains not functional

(**Bug**: When logout, website should redirect from /cart to homepage
**Initial result**: When logout, website stays at homepage)

**Images**
image
image

**Review by NghiaTranUIT — CHANGES_REQUESTED** [review]
Thanks for your PR. However, I've discovered a lot of bugs.

### Too many cart requests in the background
1. Opening a cart page
2. Observe that there is a lot of cart request in the Network tab

Screen_Shot_2021-08-20_at_08_29_32

**Expectation**
The cart should be called once or if it's necessary.

### Layout is broken in mobile size
1. Open the cart
2. Change the window size to mobile
Screen Shot 2021-08-20 at 08 28 39


**Expectation**
- Cart Table view should display properly in Mobile size
- Subtitle is not broken
- Checkout button is not broken

### Layout is broken in a bigger size
Screen_Shot_2021-08-20_at_08_28_50

**Expectation**
- Title movie should be left-align with the image view

### No empty label if the cart is empty
1. Remove one cart item
2. Observe that the table is empty?

Screen Shot 2021-08-20 at 08 29 42

**Expectation**
- Show the empty cart label in the table (Use secondary color and center-alignment )

**Comment by NghiaTranUIT** [comment]
### Minor bugs
- Subtotal label is not rounded
- The heigh of the table cart is too small (Only able to display 3 items)

Screen Shot 2021-08-20 at 08 44 35

**Expectation**
- The subtotal should be rounded up to 2 decimals.
- Please increase the height of the table, so it can display 5 items at least

**Comment by DanCat6300** [comment]
> ### Minor bugs
> * Subtotal label is not rounded
> * The heigh of the table cart is too small (Only able to display 3 items)
> 
> Screen Shot 2021-08-20 at 08 44 35
> 
> **Expectation**
> 
> * The subtotal should be rounded up to 2 decimals.
> * Please increase the height of the table, so it can display 5 items at least

The height of the label is limited to prevent becoming too large. Scrollbars will be activated instead so users can scroll 

Capture

**Comment by DanCat6300** [comment]
**Description**
- Added message when cart is empty 
- Increased cart box size
- Movie name, publish year and duration now aligned left with thumbnail 
- Responsiveness is improved

**Remaining bugs, may need support:**
- Infinite useEffect loop that fetches data constantly
- Responsiveness is not perfect

**Comment by DanCat6300** [comment]
**Changelog:**
- Fix infinite data fetching loop.
- Improve layout logic of Filtered by Category and Search page
- Number badge on Cart icon shows the number of items in Cart
- Number badge will update when the number of items in Cart changes

**Review by NghiaTranUIT — CHANGES_REQUESTED** [review]
Thanks for your work. The majority of issues are fixed. However, when you fix a "multiple" Cart endpoint, it introduces another bug on the Product Detail.

## Cart count does not update on Product Page
Screen_Shot_2021-08-23_at_12_25_51

**Review by NghiaTranUIT — APPROVED** [review]

**Pull request merged**
